### ISSUE TITLE
ASCOM Standards Web Site Updated

### ISSUE THREAD

**Issue by Peter-Simpson** [brets-astro/sxascom-releases#1]
Hi Brett,

We've updated the web site to point here but aren't sure that we have a correct email address for you, so I'm raising this issue to let you know that we've updated the site.

Best wishes, Peter

**Comment by bNaDES66** [comment]
I am new to Ascom and need to know if there is an available driver for SX Lodestar X2.

Eduardo Garcia

**Comment by Peter-Simpson** [comment]
Hi Eduardo,

Sorry I don't know, I suggest that you direct your question to Starlight Xpress using their contact page: [SX Support](https://www.sxccd.com/contact/).

I'm closing this request because its original purpose to inform Brett has been served.

Best wishes, Peter
